In [1]:
import pandas as pd

In [2]:
encuesta=pd.read_csv("/home/vicente/Desktop/Projecto final encuesta/DA3242.txt",delimiter= '\t', header=None)

In [3]:
encuesta.head()

                                                   0
0  3242    116 1 5951 0  0   01124321313 818 8121...
1  3242    216 1 5951 0  0   012333128 11898 1451...
2  3242    316 1 5951 0  0   014454799 1192219229...
3  3242    416 1 5951 0  0   01133317919 198 1 91...
4  3242    516 1 5951 0  0   099939138 1181212189...

In [4]:
print(type(encuesta[0:1].values))

<class 'numpy.ndarray'>

In [5]:
#"P15": [130,131], "P16": [132,133], "P17": [134,135], "P18": [136,136], "P18A": [137,138], "P19": [139,140], "P2001": [141,142], "P2002": [143,144],"P2003": [145,146], "P2004" :[147,148], "P2005": [149,150], "P2006": [151,152], "P2007": [153,154], "P2008": [155,156],"P2009": [157,158],"P2010": [159,160], "P2011": [161,162], "P2012": [163,164], "P2013": [165,166], "P2014": [167,168], "P2015": [169,170], "P2016": [171,172],"P2017": [173,174], "P2018": [175,176], "P2019": [177,178], "P2020": [179,180], "P21": [181,182], "P21A": [183,184], "P22": [185,185], "P23": [186,187],"P24": [188,188], "P24A": [189,190], "P25": [191,191], "P25A":[192,193], "P26":[194,194], "P27": [195,195], "P28": [196,196], "P29": [197,197], "P30": [198,198], "P30A": [199,199], "P31":[200,200],"E101": [201,202], "E102": [203,204], "E103": [205,206], "E2": [207,209], "E3": [210,210], "C1": [211,211], "C1A": [212,213], "PESO": [214,220],"P9BCOMR": [221,224], "P10R": [225,226], "P10AR": [227,228], "VOTOSIMG": [229,230], "P18AR": [231,232], "RECUERDO": [233,234], "P9BCOM": [235,238],"P14R": [239,240], "P15R": [241,242], "P16R": [243,244], "ESTUDIOS": [245,245], "PESOCCAA": [246,252]}

In [6]:
diccionario_cortes={"ESTU": [1,4], "CUES": [5,9], "CCAA":[10,11], "PROV": [12,13], "MUN": [14,16], "TAMUNI": [17,17], "CAPITAL": [18,18], "DISTR": [19,20], "SECCION": [21,23],"ENTREV": [24,27], "P0A": [28,28], "P1": [29,29], "P2": [30,30], "P3": [31,31], "P4": [32,32], "P501": [33,33], "P502": [34,34], "P503": [35,35], "P601": [36,37], "P602": [38,39], "P603": [40,41],"P701": [42,43], "P702": [44,45], "P703": [46,47], "P801": [48,48], "P802": [49,49], "P803": [50,50], "P804": [51,51], "P805": [52,52], "P806": [53,53], "P807": [54,54], "P808": [55,55],"P809": [56,56], "P810": [57,57], "P811": [58,58], "P812": [59,59], "P813": [60,60], "P814":[61,61], "P815": [62,62], "P816": [63,63], "P9": [64,64], "P9A":[65,65], "P9B01": [66,67], "P9B02": [68,69],"P10": [70,71], "P10A": [72,73], "P1101": [74,75], "P1102": [76,77], "P1103": [78,79], "P1104": [80,81], "P1105": [82,83], "P1106": [84,85],"P12":[86,87], "P1301": [88,89], "P1302": [90,91], "P1303": [92,93], "P1304": [94,95], "P1305": [96,97], "P1306": [98,99], "P1307": [100,101],"P1308": [102,103], "P1309": [104,105], "P1310": [106,107], "P1311": [108,109], "P1312": [110,111], "P1313": [112,113], "P1314": [114,115],"P1315": [116,117], "P1316": [118,119], "P1317": [120,121], "P1318": [122,123], "P1319": [124,125], "P1320": [126,127], "P14": [128,129],"P15": [130,131], "P16": [132,133], "P17": [134,135], "P18": [136,136], "P18A": [137,138], "P19": [139,140], "P2001": [141,142], "P2002": [143,144],"P2003": [145,146], "P2004" :[147,148], "P2005": [149,150], "P2006": [151,152], "P2007": [153,154], "P2008": [155,156],"P2009": [157,158],"P2010": [159,160], "P2011": [161,162], "P2012": [163,164], "P2013": [165,166], "P2014": [167,168], "P2015": [169,170], "P2016": [171,172],"P2017": [173,174], "P2018": [175,176], "P2019": [177,178], "P2020": [179,180], "P21": [181,182], "P21A": [183,184], "P22": [185,185], "P23": [186,187],"P24": [188,188], "P24A": [189,190], "P25": [191,191], "P25A":[192,193], "P26":[194,194], "P27": [195,195], "P28": [196,196], "P29": [197,197], "P30": [198,198], "P30A": [199,199], "P31":[200,200],"E101": [201,202], "E102": [203,204], "E103": [205,206], "E2": [207,209], "E3": [210,210], "C1": [211,211], "C1A": [212,213], "PESO": [214,220],"P9BCOMR": [221,224], "P10R": [225,226], "P10AR": [227,228], "VOTOSIMG": [229,230], "P18AR": [231,232], "RECUERDO": [233,234], "P9BCOM": [235,238],"P14R": [239,240], "P15R": [241,242], "P16R": [243,244], "ESTUDIOS": [245,245], "PESOCCAA": [246,252]}
import operator
columnas = {}
resultado = sorted(diccionario_cortes.items(), key=operator.itemgetter(1))

## O resultado = sorted(miDic.items(), key=operator.itemgetter(1)) dependediendo de por que lo quieras ordenar
for item in resultado:
## Entre llaves se ingresa la nueva clave que se obtiene de cada elemento de la lista resultante
## y se pide el elemento 0 de cada uno que corresponder√≠a a la clave
    nueva_clave = item[0]
## Mientras que en la tupla la posicion 1 guarda la informacion correspondiente al valor
    nuevo_valor = item[1]
    columnas[nueva_clave] = nuevo_valor

In [7]:
columnas

{'C1': [211, 211],
 'C1A': [212, 213],
 'CAPITAL': [18, 18],
 'CCAA': [10, 11],
 'CUES': [5, 9],
 'DISTR': [19, 20],
 'E101': [201, 202],
 'E102': [203, 204],
 'E103': [205, 206],
 'E2': [207, 209],
 'E3': [210, 210],
 'ENTREV': [24, 27],
 'ESTU': [1, 4],
 'ESTUDIOS': [245, 245],
 'MUN': [14, 16],
 'P0A': [28, 28],
 'P1': [29, 29],
 'P10': [70, 71],
 'P10A': [72, 73],
 'P10AR': [227, 228],
 'P10R': [225, 226],
 'P1101': [74, 75],
 'P1102': [76, 77],
 'P1103': [78, 79],
 'P1104': [80, 81],
 'P1105': [82, 83],
 'P1106': [84, 85],
 'P12': [86, 87],
 'P1301': [88, 89],
 'P1302': [90, 91],
 'P1303': [92, 93],
 'P1304': [94, 95],
 'P1305': [96, 97],
 'P1306': [98, 99],
 'P1307': [100, 101],
 'P1308': [102, 103],
 'P1309': [104, 105],
 'P1310': [106, 107],
 'P1311': [108, 109],
 'P1312': [110, 111],
 'P1313': [112, 113],
 'P1314': [114, 115],
 'P1315': [116, 117],
 'P1316': [118, 119],
 'P1317': [120, 121],
 'P1318': [122, 123],
 'P1319': [124, 125],
 'P1320': [126, 127],
 'P14': [128, 129],
 'P14R': [239, 240],
 'P15': [130, 131],
 'P15R': [241, 242],
 'P16': [132, 133],
 'P16R': [243, 244],
 'P17': [134, 135],
 'P18': [136, 136],
 'P18A': [137, 138],
 'P18AR': [231, 232],
 'P19': [139, 140],
 'P2': [30, 30],
 'P2001': [141, 142],
 'P2002': [143, 144],
 'P2003': [145, 146],
 'P2004': [147, 148],
 'P2005': [149, 150],
 'P2006': [151, 152],
 'P2007': [153, 154],
 'P2008': [155, 156],
 'P2009': [157, 158],
 'P2010': [159, 160],
 'P2011': [161, 162],
 'P2012': [163, 164],
 'P2013': [165, 166],
 'P2014': [167, 168],
 'P2015': [169, 170],
 'P2016': [171, 172],
 'P2017': [173, 174],
 'P2018': [175, 176],
 'P2019': [177, 178],
 'P2020': [179, 180],
 'P21': [181, 182],
 'P21A': [183, 184],
 'P22': [185, 185],
 'P23': [186, 187],
 'P24': [188, 188],
 'P24A': [189, 190],
 'P25': [191, 191],
 'P25A': [192, 193],
 'P26': [194, 194],
 'P27': [195, 195],
 'P28': [196, 196],
 'P29': [197, 197],
 'P3': [31, 31],
 'P30': [198, 198],
 'P30A': [199, 199],
 'P31': [200, 200],
 'P4': [32, 32],
 'P501': [33, 33],
 'P502': [34, 34],
 'P503': [35, 35],
 'P601': [36, 37],
 'P602': [38, 39],
 'P603': [40, 41],
 'P701': [42, 43],
 'P702': [44, 45],
 'P703': [46, 47],
 'P801': [48, 48],
 'P802': [49, 49],
 'P803': [50, 50],
 'P804': [51, 51],
 'P805': [52, 52],
 'P806': [53, 53],
 'P807': [54, 54],
 'P808': [55, 55],
 'P809': [56, 56],
 'P810': [57, 57],
 'P811': [58, 58],
 'P812': [59, 59],
 'P813': [60, 60],
 'P814': [61, 61],
 'P815': [62, 62],
 'P816': [63, 63],
 'P9': [64, 64],
 'P9A': [65, 65],
 'P9B01': [66, 67],
 'P9B02': [68, 69],
 'P9BCOM': [235, 238],
 'P9BCOMR': [221, 224],
 'PESO': [214, 220],
 'PESOCCAA': [246, 252],
 'PROV': [12, 13],
 'RECUERDO': [233, 234],
 'SECCION': [21, 23],
 'TAMUNI': [17, 17],
 'VOTOSIMG': [229, 230]}

In [8]:
def get_intervals(x, a, b): 
    try: 
        return x[a:b]
    except: 
        print(x, a, b)

for a in columnas:
    encuesta[a] = encuesta[0].apply(lambda x: get_intervals(x, columnas[a][0]-1, columnas[a][1]))
encuesta.head()

,0,P1304,P19,CCAA,CAPITAL,P27,P2004,P603,P1308,P26,...,P15R,P2002,P10,P1106,P2010,P9B01,RECUERDO,P807,P1302,P14
0,3242 116 1 5951 0 0 01124321313 818 8121...,0,4,16,1,1,6,18,,2,...,1,4,94,2,0,0,2,8,3,2
1,3242 216 1 5951 0 0 012333128 11898 1451...,3,6,16,1,1,6,98,,1,...,1,4,1,3,0,0,1,5,2,1
2,3242 316 1 5951 0 0 014454799 1192219229...,0,98,16,1,1,98,22,,5,...,98,98,97,1,0,0,97,5,0,97
3,3242 416 1 5951 0 0 01133317919 198 1 91...,0,4,16,1,2,6,98,,5,...,1,4,2,3,0,0,97,8,5,3
4,3242 516 1 5951 0 0 099939138 1181212189...,3,4,16,1,1,5,12,,4,...,1,5,94,4,0,0,97,3,3,5

In [9]:
encuesta.drop(0, axis=1, inplace=True)

In [13]:
def get_numeric(x):
    try:
        return int(x)
    except:
        return 0
for a in columnas:
    encuesta[a] = encuesta[a].apply(get_numeric)
    
encuesta.head()

,P1304,P19,CCAA,CAPITAL,P27,P2004,P603,P1308,P26,P25,...,P15R,P2002,P10,P1106,P2010,P9B01,RECUERDO,P807,P1302,P14
0,0,4,16,1,1,6,18,0,2,2,...,1,4,94,2,0,0,2,8,3,2
1,3,6,16,1,1,6,98,0,1,3,...,1,4,1,3,0,0,1,5,2,1
2,0,98,16,1,1,98,22,0,5,1,...,98,98,97,1,0,0,97,5,0,97
3,0,4,16,1,2,6,98,0,5,1,...,1,4,2,3,0,0,97,8,5,3
4,3,4,16,1,1,5,12,0,4,2,...,1,5,94,4,0,0,97,3,3,5

In [14]:
encuesta.describe()

,P1304,P19,CCAA,CAPITAL,P27,P2004,P603,P1308,P26,P25,...,P15R,P2002,P10,P1106,P2010,P9B01,RECUERDO,P807,P1302,P14
count,16194.000000,16194.000000,16194.000000,16194.000000,16194.000000,16194.000000,16194.000000,16194.000000,16194.000000,16194.000000,...,16194.000000,16194.000000,16194.000000,16194.000000,16194.000000,16194.000000,16194.000000,16194.000000,16194.000000,16194.000000
mean,11.172286,19.203470,7.968013,2.502594,1.339508,25.918797,35.512041,1.298753,2.568544,2.410461,...,34.735211,19.987032,49.050327,12.182969,3.497653,11.906262,37.327220,5.935408,11.860133,30.962702
std,27.735368,33.938104,4.803683,0.765397,0.692943,37.139849,37.332609,10.091787,1.578714,1.871112,...,45.447656,35.287668,45.513918,26.453548,17.514480,30.620572,43.591846,2.110784,27.040804,42.277677
min,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000
25%,0.000000,4.000000,4.000000,2.000000,1.000000,6.000000,9.000000,0.000000,2.000000,1.000000,...,2.000000,3.000000,2.000000,2.000000,0.000000,0.000000,2.000000,4.000000,0.000000,2.000000
50%,1.000000,5.000000,8.000000,3.000000,1.000000,7.000000,16.000000,0.000000,2.000000,2.000000,...,2.000000,4.000000,18.000000,5.000000,0.000000,0.000000,8.000000,5.000000,4.000000,4.000000
75%,6.000000,7.000000,11.000000,3.000000,2.000000,10.000000,46.000000,0.000000,4.000000,4.000000,...,98.000000,6.000000,94.000000,6.000000,0.000000,2.000000,97.000000,8.000000,8.000000,97.000000
max,99.000000,99.000000,19.000000,3.000000,9.000000,99.000000,99.000000,99.000000,9.000000,9.000000,...,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000,9.000000,99.000000,99.000000

In [15]:
encuesta.PESO.value_counts()

0    16194
Name: PESO, dtype: int64