In [1]:
#importamos las librerias que van a hacer falta
import pandas as pd

In [2]:
#abrimos la encuesta
encuesta=pd.read_csv("../trabajo final macroencuesta/DA3242",delimiter= '\t', header=None)

In [3]:
#una peculiaridad que tiene es que las columnas no están separadas por un simbolo sino que están juntas 
#y en el libro de código te indica donde empieza y termina una columna
encuesta.head()

                                                   0
0  3242    116 1 5951 0  0   01124321313 818 8121...
1  3242    216 1 5951 0  0   012333128 11898 1451...
2  3242    316 1 5951 0  0   014454799 1192219229...
3  3242    416 1 5951 0  0   01133317919 198 1 91...
4  3242    516 1 5951 0  0   099939138 1181212189...

In [4]:
#Creamos el diccionario con el nombre de las columnas y donde se realizan los cortes 
columnas={"ESTU": [1,4], "CUES": [5,9], "CCAA":[10,11], "PROV": [12,13], "MUN": [14,16], "TAMUNI": [17,17], "CAPITAL": [18,18], "DISTR": [19,20], "SECCION": [21,23],"ENTREV": [24,27], "P0A": [28,28], "P1": [29,29], "P2": [30,30], "P3": [31,31], "P4": [32,32], "P501": [33,33], "P502": [34,34], "P503": [35,35], "P601": [36,37], "P602": [38,39], "P603": [40,41],"P701": [42,43], "P702": [44,45], "P703": [46,47], "P801": [48,48], "P802": [49,49], "P803": [50,50], "P804": [51,51], "P805": [52,52], "P806": [53,53], "P807": [54,54], "P808": [55,55],"P809": [56,56], "P810": [57,57], "P811": [58,58], "P812": [59,59], "P813": [60,60], "P814":[61,61], "P815": [62,62], "P816": [63,63], "P9": [64,64], "P9A":[65,65], "P9B01": [66,67], "P9B02": [68,69],"P10": [70,71], "P10A": [72,73], "P1101": [74,75], "P1102": [76,77], "P1103": [78,79], "P1104": [80,81], "P1105": [82,83], "P1106": [84,85],"P12":[86,87], "P1301": [88,89], "P1302": [90,91], "P1303": [92,93], "P1304": [94,95], "P1305": [96,97], "P1306": [98,99], "P1307": [100,101],"P1308": [102,103], "P1309": [104,105], "P1310": [106,107], "P1311": [108,109], "P1312": [110,111], "P1313": [112,113], "P1314": [114,115],"P1315": [116,117], "P1316": [118,119], "P1317": [120,121], "P1318": [122,123], "P1319": [124,125], "P1320": [126,127], "P14": [128,129],"P15": [130,131], "P16": [132,133], "P17": [134,135], "P18": [136,136], "P18A": [137,138], "P19": [139,140], "P2001": [141,142], "P2002": [143,144],"P2003": [145,146], "P2004" :[147,148], "P2005": [149,150], "P2006": [151,152], "P2007": [153,154], "P2008": [155,156],"P2009": [157,158],"P2010": [159,160], "P2011": [161,162], "P2012": [163,164], "P2013": [165,166], "P2014": [167,168], "P2015": [169,170], "P2016": [171,172],"P2017": [173,174], "P2018": [175,176], "P2019": [177,178], "P2020": [179,180], "P21": [181,182], "P21A": [183,184], "P22": [185,185], "P23": [186,187],"P24": [188,188], "P24A": [189,190], "P25": [191,191], "P25A":[192,193], "P26":[194,194], "P27": [195,195], "P28": [196,196], "P29": [197,197], "P30": [198,198], "P30A": [199,199], "P31":[200,200],"E101": [201,202], "E102": [203,204], "E103": [205,206], "E2": [207,209], "E3": [210,210], "C1": [211,211], "C1A": [212,213], "PESO": [214,220],"P9BCOMR": [221,224], "P10R": [225,226], "P10AR": [227,228], "VOTOSIMG": [229,230], "P18AR": [231,232], "RECUERDO": [233,234], "P9BCOM": [235,238],"P14R": [239,240], "P15R": [241,242], "P16R": [243,244], "ESTUDIOS": [245,245], "PESOCCAA": [246,252]}

In [5]:
#ordenamos el diccionario
#import operator
#columnas = {}
#resultado = sorted(diccionario_cortes.items(), key=operator.itemgetter(1))
#for item in resultado:
## Entre llaves se ingresa la nueva clave que se obtiene de cada elemento de la lista resultante
## y se pide el elemento 0 de cada uno que correspondería a la clave
    #nueva_clave = item[0]
## Mientras que en la tupla la posicion 1 guarda la informacion correspondiente al valor
    #nuevo_valor = item[1]
    #columnas[nueva_clave] = nuevo_valor

In [6]:
#aplicamos los intervalos del diccionario en el dataFrame que hemos obtenido para poder crear las columnas
def get_intervals(x, a, b): 
    try: 
        return x[a:b]
    except: 
        print(x, a, b)

for a in columnas:
    encuesta[a] = encuesta[0].apply(lambda x: get_intervals(x, columnas[a][0]-1, columnas[a][1]))
encuesta.head()

,0,P814,P503,E3,P22,P2002,P25A,MUN,P21,P3,...,P703,P811,ESTUDIOS,ENTREV,DISTR,P702,P10A,P2016,P807,P2003
0,3242 116 1 5951 0 0 01124321313 818 8121...,8,3,1,1,4,0,59,5,4,...,13,8,6,0,0,12,98,0,8,3
1,3242 216 1 5951 0 0 012333128 11898 1451...,8,8,1,2,4,0,59,1,3,...,18,8,2,0,0,45,0,0,5,1
2,3242 316 1 5951 0 0 014454799 1192219229...,5,9,2,2,98,2,59,97,5,...,98,5,6,0,0,22,97,0,5,98
3,3242 416 1 5951 0 0 01133317919 198 1 91...,8,9,1,2,4,11,59,6,3,...,18,8,5,0,0,9,0,0,8,3
4,3242 516 1 5951 0 0 099939138 1181212189...,8,8,2,2,5,0,59,98,3,...,98,8,5,0,0,18,98,0,3,3

In [7]:
#Eliminamos la columna 0, dado que ya no nos sirve
def drop_columna(data,columna,axis=1,inplace=True):
    return data.drop(columna, axis=1, inplace=True)
drop_columna(encuesta,0)

In [8]:
#convertimos las columnas en numericas 
def get_numeric(x):
    try:
        return int(x)
    except:
        return 0
for a in columnas:
    encuesta[a] = encuesta[a].apply(get_numeric)
    
encuesta.head()

,P814,P503,E3,P22,P2002,P25A,MUN,P21,P3,P2,...,P703,P811,ESTUDIOS,ENTREV,DISTR,P702,P10A,P2016,P807,P2003
0,8,3,1,1,4,0,59,5,4,2,...,13,8,6,0,0,12,98,0,8,3
1,8,8,1,2,4,0,59,1,3,3,...,18,8,2,0,0,45,0,0,5,1
2,5,9,2,2,98,2,59,97,5,4,...,98,5,6,0,0,22,97,0,5,98
3,8,9,1,2,4,11,59,6,3,3,...,18,8,5,0,0,9,0,0,8,3
4,8,8,2,2,5,0,59,98,3,9,...,98,8,5,0,0,18,98,0,3,3

In [9]:
#seleccionamos las columnas que no nos interesan
columnas_para_eliminar=("ESTU","CUES","PROV","MUN","DISTR","SECCION","ENTREV","P501","P502","P503","P601","P602","P603","P701","P702","P703","P805","P806","P807","P808","P809","P810","P811","P812","P813","P814","P815","P816","P9","P9A","P9B01","P9B02","P10","P1101","P1102","P1103","P1104","P1105","P1106","P1305","P1306","P1307","P1308","P1309","P1310","P1311","P1312","P1313","P1314","P1315","P1316","P1317","P1318","P1319","P1320","P14","P15","P16","P17","P18","P18A","P2005","P2006","P2007","P2008","P2009","P2010","P2011","P2012","P2013","P2014","P2015","P2016","P2017","P2018","P2019","P2020","P21","P21A","P24A","P25A","P29","P30","P30A","P31","E101","E102","E103","E2","E3","C1","C1A","VOTOSIMG","RECUERDO","P9BCOM","P15R","P16R","P10AR","P9BCOMR","P10A","P24","P10R","P12","P18AR","PESO","PESOCCAA")
for a in columnas_para_eliminar:
    drop_columna(encuesta,a)

In [10]:
encuesta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16194 entries, 0 to 16193
Data columns (total 29 columns):
P22         16194 non-null int64
P2002       16194 non-null int64
P3          16194 non-null int64
P2          16194 non-null int64
P1304       16194 non-null int64
P2004       16194 non-null int64
P28         16194 non-null int64
P803        16194 non-null int64
P1303       16194 non-null int64
P27         16194 non-null int64
P1301       16194 non-null int64
P25         16194 non-null int64
P23         16194 non-null int64
P802        16194 non-null int64
P0A         16194 non-null int64
P2001       16194 non-null int64
P801        16194 non-null int64
P1          16194 non-null int64
CAPITAL     16194 non-null int64
CCAA        16194 non-null int64
P14R        16194 non-null int64
P26         16194 non-null int64
P4          16194 non-null int64
P804        16194 non-null int64
P19         16194 non-null int64
TAMUNI      16194 non-null int64
P1302       16194 non-null int64
ESTUDIOS    16194 non-null int64
P2003       16194 non-null int64
dtypes: int64(29)
memory usage: 3.6 MB

In [11]:
encuesta.P19.value_counts()

5     3399
3     2270
4     2205
98    1562
6     1519
7     1099
99     945
2      911
1      857
8      852
9      327
10     248
Name: P19, dtype: int64

In [12]:
limpieza9=("ESTUDIOS","P0A","P1","P2","P3","P4","P801","P802","P803","P804","P23","P25","P26","P27","P28")
limpieza99=("P1301","P1302","P1303","P1304","P14R","P2001","P2002","P2003","P2004",)

In [13]:
def drop_file(data,pregunta,valor):
    data = data[data[pregunta] != valor]
    return data

In [14]:
#Eliminación de NC-8 ó 88 y NS - 9 ó 99
for a in limpieza9:
    encuesta = drop_file(encuesta,a,8)
    encuesta = drop_file(encuesta,a,9)
for a in limpieza99:
    encuesta = drop_file(encuesta,a,88)
    encuesta = drop_file(encuesta,a,98)
    encuesta = drop_file(encuesta,a,99)

In [15]:
#elimnación según peculiaridades de las preguntas
#quitar de Estudios "otros"
encuesta = drop_file(encuesta,"ESTUDIOS",7)
encuesta.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9731 entries, 0 to 16191
Data columns (total 29 columns):
P22         9731 non-null int64
P2002       9731 non-null int64
P3          9731 non-null int64
P2          9731 non-null int64
P1304       9731 non-null int64
P2004       9731 non-null int64
P28         9731 non-null int64
P803        9731 non-null int64
P1303       9731 non-null int64
P27         9731 non-null int64
P1301       9731 non-null int64
P25         9731 non-null int64
P23         9731 non-null int64
P802        9731 non-null int64
P0A         9731 non-null int64
P2001       9731 non-null int64
P801        9731 non-null int64
P1          9731 non-null int64
CAPITAL     9731 non-null int64
CCAA        9731 non-null int64
P14R        9731 non-null int64
P26         9731 non-null int64
P4          9731 non-null int64
P804        9731 non-null int64
P19         9731 non-null int64
TAMUNI      9731 non-null int64
P1302       9731 non-null int64
ESTUDIOS    9731 non-null int64
P2003       9731 non-null int64
dtypes: int64(29)
memory usage: 2.2 MB

In [16]:
#Estas variables la escala en la cual están medidas es inversa,es decir, la mejor valoración es el número 
#mas bajo, por lo que voy a múltiplicarlas por -1 para dar la vuelta a este fenómeno
inver_valores=("P1","P2","P3","P801","P802","P803","P804")

In [17]:
def inversion(data,columna):
    data[columna] = data[columna]*-1
    return data

In [18]:
for columna in inver_valores:
    encuesta = inversion(encuesta,columna)

In [19]:
encuesta.describe()

,P22,P2002,P3,P2,P1304,P2004,P28,P803,P1303,P27,...,CCAA,P14R,P26,P4,P804,P19,TAMUNI,P1302,ESTUDIOS,P2003
count,9731.000000,9731.000000,9731.000000,9731.000000,9731.000000,9731.000000,9731.000000,9731.000000,9731.000000,9731.000000,...,9731.000000,9731.000000,9731.000000,9731.000000,9731.000000,9731.000000,9731.000000,9731.000000,9731.000000,9731.000000
mean,1.460795,4.098448,-3.969273,-2.176446,2.611962,6.899188,1.161546,-3.839893,2.069366,1.285274,...,8.041517,18.632926,2.635803,3.711849,-3.679170,7.873189,3.577330,3.667352,4.161135,2.279108
std,0.498486,1.549913,0.869833,1.018636,3.092921,1.749118,0.448596,0.967857,2.918949,0.451568,...,4.809626,33.705933,1.451061,0.852421,0.952757,17.262842,1.609343,3.611621,1.516451,1.428600
min,1.000000,1.000000,-5.000000,-4.000000,0.000000,1.000000,1.000000,-5.000000,0.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,-5.000000,1.000000,1.000000,0.000000,1.000000,1.000000
25%,1.000000,3.000000,-5.000000,-3.000000,0.000000,6.000000,1.000000,-5.000000,0.000000,1.000000,...,4.000000,2.000000,2.000000,3.000000,-4.000000,3.000000,2.000000,0.000000,3.000000,1.000000
50%,1.000000,4.000000,-4.000000,-2.000000,1.000000,7.000000,1.000000,-4.000000,0.000000,1.000000,...,8.000000,3.000000,2.000000,4.000000,-4.000000,5.000000,3.000000,3.000000,4.000000,2.000000
75%,2.000000,5.000000,-3.000000,-1.000000,5.000000,8.000000,1.000000,-3.000000,4.000000,2.000000,...,11.000000,9.000000,4.000000,4.000000,-3.000000,6.000000,5.000000,7.000000,6.000000,3.000000
max,2.000000,10.000000,-1.000000,-1.000000,10.000000,10.000000,3.000000,-1.000000,10.000000,2.000000,...,19.000000,97.000000,6.000000,5.000000,-1.000000,99.000000,7.000000,10.000000,6.000000,10.000000

In [20]:
#prueba de correlacion,variable autoubicacion sin los nulos
encuestaauto = drop_file(encuesta,"P19",98)
encuestaauto = drop_file(encuestaauto,"P19",99)

In [21]:
correlacion = encuesta.corr()
correlacion

,P22,P2002,P3,P2,P1304,P2004,P28,P803,P1303,P27,...,CCAA,P14R,P26,P4,P804,P19,TAMUNI,P1302,ESTUDIOS,P2003
P22,1.000000,-0.004449,-0.032420,-0.035585,0.013796,0.009552,-0.002009,-0.034918,-0.041394,-0.034320,...,0.002908,-0.013096,-0.101582,0.089025,-0.016144,-0.003110,0.064088,0.029319,0.035957,0.006564
P2002,-0.004449,1.000000,-0.061706,0.102530,-0.207924,0.295270,-0.036919,0.185574,0.165870,0.012292,...,0.069117,0.082241,0.246672,0.054457,-0.262062,-0.016784,0.023730,-0.078643,0.097102,0.456949
P3,-0.032420,-0.061706,1.000000,0.064928,0.060818,-0.053085,0.032054,0.213531,0.076434,-0.029383,...,-0.011262,-0.129563,-0.043409,-0.497452,0.174868,-0.055762,0.029615,0.258236,0.018764,-0.038000
P2,-0.035585,0.102530,0.064928,1.000000,-0.043166,0.172525,-0.037251,0.158339,0.170895,-0.085616,...,0.056247,-0.142318,0.177839,-0.092175,-0.056669,-0.129749,0.062710,0.034413,0.254601,0.068875
P1304,0.013796,-0.207924,0.060818,-0.043166,1.000000,-0.341267,0.024296,-0.277114,-0.205583,-0.021546,...,-0.062009,-0.088832,-0.232072,-0.094962,0.593653,0.002940,0.003861,-0.136004,0.002464,-0.231647
P2004,0.009552,0.295270,-0.053085,0.172525,-0.341267,1.000000,-0.020109,0.296813,0.279142,-0.013682,...,0.145315,-0.008959,0.286357,0.058958,-0.385649,-0.072470,0.011624,0.077794,0.079977,0.264868
P28,-0.002009,-0.036919,0.032054,-0.037251,0.024296,-0.020109,1.000000,-0.006791,-0.030457,-0.066184,...,-0.029879,-0.041000,-0.088177,-0.016133,0.014345,-0.015802,-0.040795,0.025242,-0.133146,-0.028988
P803,-0.034918,0.185574,0.213531,0.158339,-0.277114,0.296813,-0.006791,1.000000,0.580750,0.012591,...,0.038048,-0.113192,0.258281,-0.112995,-0.153344,-0.127174,0.036127,0.309609,0.056576,0.188661
P1303,-0.041394,0.165870,0.076434,0.170895,-0.205583,0.279142,-0.030457,0.580750,1.000000,0.023816,...,0.036618,-0.103894,0.325604,-0.009314,-0.224451,-0.134622,0.083975,0.270344,0.097082,0.148878
P27,-0.034320,0.012292,-0.029383,-0.085616,-0.021546,-0.013682,-0.066184,0.012591,0.023816,1.000000,...,-0.059258,0.025031,0.053330,0.066992,-0.009943,0.031405,-0.102201,0.023596,-0.072387,0.023610
P1301,0.011760,-0.257895,0.014970,-0.064791,0.440165,-0.346846,0.050948,-0.377983,-0.310105,-0.037415,...,-0.052310,-0.112447,-0.364359,-0.053481,0.416026,0.031689,-0.051707,-0.305522,-0.101088,-0.285879
P25,0.201881,-0.023644,0.030618,-0.071681,0.007505,-0.054840,0.021896,-0.009566,-0.015473,-0.002992,...,-0.033184,-0.017834,-0.040556,0.047249,0.035929,0.003313,0.008308,0.034980,-0.190923,-0.029521
P23,0.004380,-0.076996,0.042153,-0.056402,-0.031640,-0.020183,0.173759,-0.061150,-0.126158,-0.166872,...,0.028791,-0.092170,-0.317306,-0.004286,0.023615,0.001274,-0.013880,0.070110,-0.364450,-0.074088
P802,0.012109,-0.051789,0.382543,0.041006,-0.132161,0.074399,0.026554,0.498450,0.228685,-0.000672,...,-0.015888,-0.189347,-0.005387,-0.239667,0.058342,-0.109880,0.011286,0.608463,-0.093679,0.024663
P0A,0.021796,0.007971,0.080838,0.003262,0.043313,-0.015598,-0.005114,0.019863,0.012876,0.025202,...,0.028513,-0.000703,-0.015736,-0.086184,0.052822,0.013381,0.061845,0.035954,0.028364,0.031935
P2001,0.027575,0.145820,-0.036130,0.120401,-0.266204,0.566807,-0.002890,0.229903,0.223678,0.014721,...,0.130597,-0.044201,0.212808,0.039996,-0.286217,-0.062403,0.003683,0.095569,0.034846,0.172884
P801,0.000749,-0.286389,0.136513,-0.105978,0.406324,-0.404338,0.049423,-0.290812,-0.331783,-0.014513,...,-0.100157,-0.098545,-0.377575,-0.152179,0.617181,0.041284,-0.049648,-0.213265,-0.108501,-0.287469
P1,-0.059778,0.096538,0.123460,0.622683,-0.069918,0.171524,-0.049176,0.203553,0.209010,-0.074998,...,0.054980,-0.161006,0.204191,-0.126405,-0.063616,-0.134248,0.085931,0.051552,0.278964,0.051215
CAPITAL,-0.047868,0.012078,-0.035784,-0.030751,-0.014591,0.021548,0.027412,-0.002405,-0.047572,0.120029,...,-0.156041,0.008199,-0.019451,0.036525,-0.005974,0.017303,-0.749022,-0.012464,-0.137084,0.021462
CCAA,0.002908,0.069117,-0.011262,0.056247,-0.062009,0.145315,-0.029879,0.038048,0.036618,-0.059258,...,1.000000,0.016543,0.073707,-0.022802,-0.089928,-0.024034,0.063651,-0.052585,0.071060,0.088239
P14R,-0.013096,0.082241,-0.129563,-0.142318,-0.088832,-0.008959,-0.041000,-0.113192,-0.103894,0.025031,...,0.016543,1.000000,0.042132,0.099384,-0.125208,0.233638,-0.010123,-0.196746,0.048661,0.065583
P26,-0.101582,0.246672,-0.043409,0.177839,-0.232072,0.286357,-0.088177,0.258281,0.325604,0.053330,...,0.073707,0.042132,1.000000,0.025242,-0.271189,-0.065869,0.064169,0.025555,0.239278,0.217954
P4,0.089025,0.054457,-0.497452,-0.092175,-0.094962,0.058958,-0.016133,-0.112995,-0.009314,0.066992,...,-0.022802,0.099384,0.025242,1.000000,-0.183163,0.049095,-0.021664,-0.125647,-0.104645,0.038874
P804,-0.016144,-0.262062,0.174868,-0.056669,0.593653,-0.385649,0.014345,-0.153344,-0.224451,-0.009943,...,-0.089928,-0.125208,-0.271189,-0.183163,1.000000,0.007229,-0.024159,-0.081822,-0.051434,-0.254265
P19,-0.003110,-0.016784,-0.055762,-0.129749,0.002940,-0.072470,-0.015802,-0.127174,-0.134622,0.031405,...,-0.024034,0.233638,-0.065869,0.049095,0.007229,1.000000,-0.007020,-0.137823,-0.040662,-0.040205
TAMUNI,0.064088,0.023730,0.029615,0.062710,0.003861,0.011624,-0.040795,0.036127,0.083975,-0.102201,...,0.063651,-0.010123,0.064169,-0.021664,-0.024159,-0.007020,1.000000,0.009138,0.173745,0.014035
P1302,0.029319,-0.078643,0.258236,0.034413,-0.136004,0.077794,0.025242,0.309609,0.270344,0.023596,...,-0.052585,-0.196746,0.025555,-0.125647,-0.081822,-0.137823,0.009138,1.000000,-0.100177,0.031801
ESTUDIOS,0.035957,0.097102,0.018764,0.254601,0.002464,0.079977,-0.133146,0.056576,0.097082,-0.072387,...,0.071060,0.048661,0.239278,-0.104645,-0.051434,-0.040662,0.173745,-0.100177,1.000000,0.068473
P2003,0.006564,0.456949,-0.038000,0.068875,-0.231647,0.264868,-0.028988,0.188661,0.148878,0.023610,...,0.088239,0.065583,0.217954,0.038874,-0.254265,-0.040205,0.014035,0.031801,0.068473,1.000000

In [22]:
import seaborn as sns
import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize = (25,25))
ax = sns.heatmap(correlacion, annot=True)
ax

In [23]:
#ver colinealidad entre las variables
def variablescolinealidad(data):
    columns_to_drop=[]                  
    for c in data.columns:
        for i in range(len(data.corr())):
            if abs(data.corr()[c][i])>0.9 and abs(data.corr()[c][i])<1:columns_to_drop.append(c)
    columns_to_drop=list(set(columns_to_drop))   
    return len(columns_to_drop)

In [24]:
variablescolinealidad(encuesta)

0

In [27]:
encuesta.reset_index().head()

,index,P22,P2002,P3,P2,P1304,P2004,P28,P803,P1303,...,CCAA,P14R,P26,P4,P804,P19,TAMUNI,P1302,ESTUDIOS,P2003
0,0,1,4,-4,-2,0,6,1,-4,1,...,16,2,2,3,-4,4,5,3,6,3
1,1,2,4,-3,-3,3,6,1,-5,1,...,16,1,1,3,-3,6,5,2,2,1
2,3,2,4,-3,-3,0,6,1,-3,4,...,16,3,5,3,-5,4,5,5,5,3
3,5,1,4,-3,-1,0,6,1,-4,0,...,16,2,4,3,-4,4,5,10,6,2
4,6,1,4,-3,-3,0,7,1,-3,2,...,16,12,5,3,-5,2,5,2,6,2

In [31]:
encuesta.to_csv("encuestalimpia.csv",header=True,index=False)