In [1]:
#importamos las librerias que van a hacer falta
import pandas as pd

In [2]:
#abrimos la encuesta
encuesta=pd.read_csv("../trabajo final macroencuesta/DA3242",delimiter= '\t', header=None)

In [3]:
#una peculiaridad que tiene es que las columnas no están separadas por un simbolo sino que están juntas 
#y en el libro de código te indica donde empieza y termina una columna
encuesta.head()

                                                   0
0  3242    116 1 5951 0  0   01124321313 818 8121...
1  3242    216 1 5951 0  0   012333128 11898 1451...
2  3242    316 1 5951 0  0   014454799 1192219229...
3  3242    416 1 5951 0  0   01133317919 198 1 91...
4  3242    516 1 5951 0  0   099939138 1181212189...

In [4]:
#Creamos el diccionario con el nombre de las columnas y donde se realizan los cortes 
columnas={"ESTU": [1,4], "CUES": [5,9], "CCAA":[10,11], "PROV": [12,13], "MUN": [14,16], "TAMUNI": [17,17], "CAPITAL": [18,18], "DISTR": [19,20], "SECCION": [21,23],"ENTREV": [24,27], "P0A": [28,28], "P1": [29,29], "P2": [30,30], "P3": [31,31], "P4": [32,32], "P501": [33,33], "P502": [34,34], "P503": [35,35], "P601": [36,37], "P602": [38,39], "P603": [40,41],"P701": [42,43], "P702": [44,45], "P703": [46,47], "P801": [48,48], "P802": [49,49], "P803": [50,50], "P804": [51,51], "P805": [52,52], "P806": [53,53], "P807": [54,54], "P808": [55,55],"P809": [56,56], "P810": [57,57], "P811": [58,58], "P812": [59,59], "P813": [60,60], "P814":[61,61], "P815": [62,62], "P816": [63,63], "P9": [64,64], "P9A":[65,65], "P9B01": [66,67], "P9B02": [68,69],"P10": [70,71], "P10A": [72,73], "P1101": [74,75], "P1102": [76,77], "P1103": [78,79], "P1104": [80,81], "P1105": [82,83], "P1106": [84,85],"P12":[86,87], "P1301": [88,89], "P1302": [90,91], "P1303": [92,93], "P1304": [94,95], "P1305": [96,97], "P1306": [98,99], "P1307": [100,101],"P1308": [102,103], "P1309": [104,105], "P1310": [106,107], "P1311": [108,109], "P1312": [110,111], "P1313": [112,113], "P1314": [114,115],"P1315": [116,117], "P1316": [118,119], "P1317": [120,121], "P1318": [122,123], "P1319": [124,125], "P1320": [126,127], "P14": [128,129],"P15": [130,131], "P16": [132,133], "P17": [134,135], "P18": [136,136], "P18A": [137,138], "P19": [139,140], "P2001": [141,142], "P2002": [143,144],"P2003": [145,146], "P2004" :[147,148], "P2005": [149,150], "P2006": [151,152], "P2007": [153,154], "P2008": [155,156],"P2009": [157,158],"P2010": [159,160], "P2011": [161,162], "P2012": [163,164], "P2013": [165,166], "P2014": [167,168], "P2015": [169,170], "P2016": [171,172],"P2017": [173,174], "P2018": [175,176], "P2019": [177,178], "P2020": [179,180], "P21": [181,182], "P21A": [183,184], "P22": [185,185], "P23": [186,187],"P24": [188,188], "P24A": [189,190], "P25": [191,191], "P25A":[192,193], "P26":[194,194], "P27": [195,195], "P28": [196,196], "P29": [197,197], "P30": [198,198], "P30A": [199,199], "P31":[200,200],"E101": [201,202], "E102": [203,204], "E103": [205,206], "E2": [207,209], "E3": [210,210], "C1": [211,211], "C1A": [212,213], "PESO": [214,220],"P9BCOMR": [221,224], "P10R": [225,226], "P10AR": [227,228], "VOTOSIMG": [229,230], "P18AR": [231,232], "RECUERDO": [233,234], "P9BCOM": [235,238],"P14R": [239,240], "P15R": [241,242], "P16R": [243,244], "ESTUDIOS": [245,245], "PESOCCAA": [246,252]}

In [5]:
#ordenamos el diccionario
#import operator
#columnas = {}
#resultado = sorted(diccionario_cortes.items(), key=operator.itemgetter(1))
#for item in resultado:
## Entre llaves se ingresa la nueva clave que se obtiene de cada elemento de la lista resultante
## y se pide el elemento 0 de cada uno que correspondería a la clave
    #nueva_clave = item[0]
## Mientras que en la tupla la posicion 1 guarda la informacion correspondiente al valor
    #nuevo_valor = item[1]
    #columnas[nueva_clave] = nuevo_valor

In [6]:
#aplicamos los intervalos del diccionario en el dataFrame que hemos obtenido para poder crear las columnas
def get_intervals(x, a, b): 
    try: 
        return x[a:b]
    except: 
        print(x, a, b)

for a in columnas:
    encuesta[a] = encuesta[0].apply(lambda x: get_intervals(x, columnas[a][0]-1, columnas[a][1]))
encuesta.head()

,0,P2016,CCAA,P1309,ESTUDIOS,P15,P1311,MUN,DISTR,P702,...,P2013,P808,P9B02,P27,ESTU,P10,P12,P701,P1320,P1305
0,3242 116 1 5951 0 0 01124321313 818 8121...,0,16,,6,1,0,59,0,12,...,0,8,0,1,3242,94,7,8,,0
1,3242 216 1 5951 0 0 012333128 11898 1451...,0,16,,2,1,1,59,0,45,...,0,5,0,1,3242,1,7,1,,0
2,3242 316 1 5951 0 0 014454799 1192219229...,0,16,,6,98,0,59,0,22,...,0,5,0,1,3242,97,1,19,,0
3,3242 416 1 5951 0 0 01133317919 198 1 91...,0,16,,5,1,1,59,0,9,...,0,8,0,2,3242,2,3,1,,1
4,3242 516 1 5951 0 0 099939138 1181212189...,0,16,,5,1,3,59,0,18,...,0,3,0,1,3242,94,2,12,,4

In [7]:
#Eliminamos la columna 0, dado que ya no nos sirve
def drop_columna(data,columna,axis=1,inplace=True):
    return data.drop(columna, axis=1, inplace=True)
drop_columna(encuesta,0)

In [8]:
#convertimos las columnas en numericas 
def get_numeric(x):
    try:
        return int(x)
    except:
        return 0
for a in columnas:
    encuesta[a] = encuesta[a].apply(get_numeric)
    
encuesta.head()

,P2016,CCAA,P1309,ESTUDIOS,P15,P1311,MUN,DISTR,P702,P1302,...,P2013,P808,P9B02,P27,ESTU,P10,P12,P701,P1320,P1305
0,0,16,0,6,1,0,59,0,12,3,...,0,8,0,1,3242,94,7,8,0,0
1,0,16,0,2,1,1,59,0,45,2,...,0,5,0,1,3242,1,7,1,0,0
2,0,16,0,6,98,0,59,0,22,0,...,0,5,0,1,3242,97,1,19,0,0
3,0,16,0,5,1,1,59,0,9,5,...,0,8,0,2,3242,2,3,1,0,1
4,0,16,0,5,1,3,59,0,18,3,...,0,3,0,1,3242,94,2,12,0,4

In [9]:
#seleccionamos las columnas que no nos interesan
columnas_para_eliminar=("ESTU","CUES","PROV","MUN","DISTR","SECCION","ENTREV","P501","P502","P503","P601","P602","P603","P701","P702","P703","P805","P806","P807","P808","P809","P810","P811","P812","P813","P814","P815","P816","P9","P9A","P9B01","P9B02","P10","P1101","P1102","P1103","P1104","P1105","P1106","P1305","P1306","P1307","P1308","P1309","P1310","P1311","P1312","P1313","P1314","P1315","P1316","P1317","P1318","P1319","P1320","P14","P15","P16","P17","P18","P18A","P2005","P2006","P2007","P2008","P2009","P2010","P2011","P2012","P2013","P2014","P2015","P2016","P2017","P2018","P2019","P2020","P21","P21A","P24A","P25A","P29","P30","P30A","P31","E101","E102","E103","E2","E3","C1","C1A","VOTOSIMG","RECUERDO","P9BCOM","P15R","P16R","P10AR","P9BCOMR","P10A","P24","P10R","P12","P18AR","PESO","PESOCCAA")
for a in columnas_para_eliminar:
    drop_columna(encuesta,a)

In [10]:
encuesta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16194 entries, 0 to 16193
Data columns (total 29 columns):
CCAA        16194 non-null int64
ESTUDIOS    16194 non-null int64
P1302       16194 non-null int64
P19         16194 non-null int64
P801        16194 non-null int64
P22         16194 non-null int64
P802        16194 non-null int64
P2001       16194 non-null int64
TAMUNI      16194 non-null int64
P25         16194 non-null int64
P1304       16194 non-null int64
P14R        16194 non-null int64
P23         16194 non-null int64
P2002       16194 non-null int64
P1303       16194 non-null int64
P3          16194 non-null int64
CAPITAL     16194 non-null int64
P26         16194 non-null int64
P1          16194 non-null int64
P804        16194 non-null int64
P1301       16194 non-null int64
P2003       16194 non-null int64
P803        16194 non-null int64
P4          16194 non-null int64
P2004       16194 non-null int64
P2          16194 non-null int64
P0A         16194 non-null int64
P28         16194 non-null int64
P27         16194 non-null int64
dtypes: int64(29)
memory usage: 3.6 MB

In [11]:
encuesta.P19.value_counts()

5     3399
3     2270
4     2205
98    1562
6     1519
7     1099
99     945
2      911
1      857
8      852
9      327
10     248
Name: P19, dtype: int64

In [12]:
limpieza9=("ESTUDIOS","P0A","P1","P2","P3","P4","P801","P802","P803","P804","P23","P25","P26","P27","P28")
limpieza99=("P1301","P1302","P1303","P1304","P14R","P2001","P2002","P2003","P2004",)

In [13]:
def drop_file(data,pregunta,valor):
    data = data[data[pregunta] != valor]
    return data

In [14]:
#Eliminación de NC-8 ó 88 y NS - 9 ó 99
for a in limpieza9:
    encuesta = drop_file(encuesta,a,8)
    encuesta = drop_file(encuesta,a,9)
for a in limpieza99:
    encuesta = drop_file(encuesta,a,88)
    encuesta = drop_file(encuesta,a,98)
    encuesta = drop_file(encuesta,a,99)

In [15]:
#elimnación según peculiaridades de las preguntas
#quitar de Estudios "otros"
encuesta = drop_file(encuesta,"ESTUDIOS",7)
encuesta.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9731 entries, 0 to 16191
Data columns (total 29 columns):
CCAA        9731 non-null int64
ESTUDIOS    9731 non-null int64
P1302       9731 non-null int64
P19         9731 non-null int64
P801        9731 non-null int64
P22         9731 non-null int64
P802        9731 non-null int64
P2001       9731 non-null int64
TAMUNI      9731 non-null int64
P25         9731 non-null int64
P1304       9731 non-null int64
P14R        9731 non-null int64
P23         9731 non-null int64
P2002       9731 non-null int64
P1303       9731 non-null int64
P3          9731 non-null int64
CAPITAL     9731 non-null int64
P26         9731 non-null int64
P1          9731 non-null int64
P804        9731 non-null int64
P1301       9731 non-null int64
P2003       9731 non-null int64
P803        9731 non-null int64
P4          9731 non-null int64
P2004       9731 non-null int64
P2          9731 non-null int64
P0A         9731 non-null int64
P28         9731 non-null int64
P27         9731 non-null int64
dtypes: int64(29)
memory usage: 2.2 MB

In [ ]:
#Estas variables la escala en la cual están medidas es inversa,es decir, la mejor valoración es el número 
#mas bajo, por lo que voy a múltiplicarlas por -1 para dar la vuelta a este fenómeno
"""inver_valores=("P1","P2","P3","P801","P802","P803","P804")"""

In [ ]:
"""def inversion(data,columna):
    data[columna] = data[columna]*-1
    return data
"""

In [ ]:
"""for columna in inver_valores:
    encuesta = inversion(encuesta,columna)"""

In [ ]:
#prueba de correlacion,variable autoubicacion sin los nulos
encuestaauto = drop_file(encuesta,"P19",98)
encuestaauto = drop_file(encuestaauto,"P19",99)

In [ ]:
correlacion = encuesta.corr()
correlacion

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize = (25,25))
ax = sns.heatmap(correlacion, annot=True)
ax

In [ ]:
#ver colinealidad entre las variables
def variablescolinealidad(data):
    columns_to_drop=[]                  
    for c in data.columns:
        for i in range(len(data.corr())):
            if abs(data.corr()[c][i])>0.9 and abs(data.corr()[c][i])<1:columns_to_drop.append(c)
    columns_to_drop=list(set(columns_to_drop))   
    return len(columns_to_drop)

In [ ]:
variablescolinealidad(encuesta)

In [16]:
encuesta.reset_index().head()

,index,CCAA,ESTUDIOS,P1302,P19,P801,P22,P802,P2001,TAMUNI,...,P804,P1301,P2003,P803,P4,P2004,P2,P0A,P28,P27
0,0,16,6,3,4,4,1,2,7,5,...,4,0,3,4,3,6,2,1,1,1
1,1,16,2,2,6,2,2,4,6,5,...,3,7,1,5,3,6,3,1,1,1
2,3,16,5,5,4,5,2,3,7,5,...,5,0,3,3,3,6,3,1,1,2
3,5,16,6,10,4,5,1,1,7,5,...,4,0,2,4,3,6,1,1,1,1
4,6,16,6,2,2,5,1,3,8,5,...,5,0,2,3,3,7,3,1,1,2

In [ ]:
encuesta.to_csv("encuestalimpia.csv",header=True,index=False)

In [17]:
import pandas as pd
import seaborn as sns
from sklearn.decomposition import PCA
import matplotlib
import matplotlib.pyplot as plt
from scipy import stats
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier           
from sklearn.neighbors import KNeighborsClassifier            
from sklearn.ensemble import GradientBoostingClassifier       
from sklearn.neural_network import MLPClassifier
#from sklearn.model_selection import GridSearchCV 
from sklearn import tree
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn import tree
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
import numpy as np

import statsmodels.api as sm

import statsmodels.formula.api as smf

In [18]:
def modelos(data,columnadep):
    X=data.loc[:,data.columns!= columnadep]
    y=data[columnadep]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
    
    #modelos
    lr = LogisticRegression(solver ='liblinear',max_iter=500)
    cls = svm.SVC(gamma='auto', probability=True)
    neigh3 = KNeighborsClassifier(n_neighbors=3)
    neigh5 = KNeighborsClassifier(n_neighbors=5)
    bosque=RandomForestClassifier(n_estimators=500, criterion='gini')
    gnb = GaussianNB()
    #tree = tree.DecisionTreeClassifier()
    svc = SVC(kernel='rbf', gamma='scale')
    gbc=GradientBoostingClassifier()

    #entrenando
    cls.fit(X_train, y_train)
    lr.fit(X_train, y_train)
    neigh3.fit(X_train, y_train) 
    neigh5.fit(X_train, y_train) 
    bosque.fit(X_train, y_train) 
    #tree.fit(X_train, y_train)
    gnb.fit(X_train,y_train)
    svc.fit(X_train,y_train)
    gbc.fit(X_train, y_train)



    
    
    y_predlr = lr.predict(X_test)
    y_predcls = cls.predict(X_test)
    y_pred_neigh3= neigh3.predict(X_test)
    y_pred_neigh5= neigh5.predict(X_test)
    y_pred_bosque= bosque.predict(X_test)
    #y_pred_tree= tree.predict(X_test)
    y_pred_gnd = gnb.predict(X_test)
    y_pred_svc = svc.predict(X_test)
    y_pred_gbc=gbc.predict(X_test)

    
    print("Accuracy lineal:",metrics.accuracy_score(y_test, y_predcls))
    print("Accuracy logistics:",metrics.accuracy_score(y_test, y_predlr))
    print("Accuracy neigh3:",metrics.accuracy_score(y_test, y_pred_neigh3))
    print("Accuracy neigh5:",metrics.accuracy_score(y_test, y_pred_neigh5))
    print("Accuracy bosque:",metrics.accuracy_score(y_test, y_pred_bosque))
    #print("Accuracy tree:",metrics.accuracy_score(y_test, y_pred_tree))
    print("Accuracy gnd:",metrics.accuracy_score(y_test, y_pred_gnd))
    print("Accuracy svc:",metrics.accuracy_score(y_test, y_pred_svc))
    print("Accuracy gbc:",metrics.accuracy_score(y_test, y_pred_gbc))
    


    # Your code here:
    print("matriz de confusion lineal","\n",confusion_matrix(y_test, y_predlr))
    print("matriz de confusion vecino3","\n",confusion_matrix(y_test, y_pred_neigh3))
    print("matriz de confusion vecino5","\n",confusion_matrix(y_test, y_pred_neigh5))
    print("matriz de confusion bosque","\n",confusion_matrix(y_test, y_pred_bosque))
    print("matriz de confusion gnd","\n",confusion_matrix(y_test, y_pred_gnd))
    print("matriz de confusion svc","\n",confusion_matrix(y_test, y_pred_svc))
    print("matriz de confusion gbc","\n", confusion_matrix(y_test, y_pred_gbc))

In [19]:
#elimino los valores ns y nc
encuesta = drop_file(encuesta,"P19",98)
encuesta = drop_file(encuesta,"P19",99)

In [20]:
etiquetas=[0,1,2]
cortes = [0,3,6,10]
encuesta["ideologia"] = pd.cut(encuesta['P19'],cortes, labels=etiquetas)
encuesta["ideologia"] = pd.to_numeric(encuesta["ideologia"])

In [21]:
encuesta=encuesta.drop(columns="P19")

In [22]:
cols=["P1","P2","P3","P4","P801","P802","P803","P804","P1301","P1302","P1303","P1304","P2001","P2002","P2003","P2004","P23","TAMUNI","ESTUDIOS","CAPITAL","CCAA","P0A","P14R","P22","P25","P26","P27","P28","ideologia"]
colssincat=["P1","P2","P3","P4","P801","P802","P803","P804","P1301","P1302","P1303","P1304","P2001","P2002","P2003","P2004","P23","TAMUNI","ESTUDIOS","ideologia"]

In [23]:
variables_categoricas=["CAPITAL","CCAA","P0A","P14R","P22","P25","P26","P27","P28"]

In [ ]:
encuesta2=encuesta.drop(columns=variables_categoricas)

In [ ]:
pca = PCA(n_components=2)
distribution_all=pca.fit(encuesta2.T) 
plt.figure(figsize=(8,8))
color= ['red' if ideologia == 0 
        else 'orange' if ideologia == 1
        else 'blue' if ideologia == 2
        else 'red' for ideologia in list(encuesta['ideologia'])]
plt.scatter(distribution_all.components_[0], distribution_all.components_[1],color=color,s=0.5)

In [ ]:
modelos(encuesta2,"ideologia")

In [ ]:
results = smf.ols('ideologia ~ P1 + P2 + P3 + P4 + P801 + P802 + P803 + P804 + P1301 + P1302 + P1303 + P1304 + P2001 + P2002 + P2003 + P2004 + TAMUNI+ ESTUDIOS', data=encuesta2).fit()

# Inspect the results
print(results.summary())

In [24]:
encuesta_dumf=pd.get_dummies(encuesta,columns=["CAPITAL","CCAA","P0A","P14R","P22","P25","P26","P27","P28"],drop_first=False)
encuesta_dum=pd.get_dummies(encuesta,columns=["CAPITAL","CCAA","P0A","P14R","P22","P25","P26","P27","P28"],drop_first=True)

In [25]:
modelos(encuesta_dum,"ideologia")

/home/vicente/.local/lib/python3.5/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)

Accuracy lineal: 0.7461415646620543
Accuracy logistics: 0.7285790313996807
Accuracy neigh3: 0.651942522618414
Accuracy neigh5: 0.6668440659925492
Accuracy bosque: 0.766897285790314
Accuracy gnd: 0.5678552421500799
Accuracy svc: 0.7019691325172964
Accuracy gbc: 0.7594465141032464
matriz de confusion lineal
 [[410 192   0]
 [126 687  89]
 [  4  99 272]]
matriz de confusion vecino3
 [[392 206   4]
 [196 598 108]
 [ 15 125 235]]
matriz de confusion vecino5
 [[393 207   2]
 [182 623  97]
 [ 10 128 237]]
matriz de confusion bosque
 [[452 150   0]
 [117 716  69]
 [  3  99 273]]
matriz de confusion gnd
 [[438 139  25]
 [190 285 427]
 [  5  26 344]]
matriz de confusion svc
 [[407 193   2]
 [144 672  86]
 [  5 130 240]]
matriz de confusion gbc
 [[451 151   0]
 [123 700  79]
 [  3  96 276]]

In [ ]:
results = smf.ols('ideologia ~  P1 + P2 + P3 + P4 + P801 + P802 + P803+ P804 +P1301 + P1302 + P1303 +  P1304 + P2001 +P2002 + P2003 + P2004  + P23  + TAMUNI  + ESTUDIOS   + CAPITAL_2 + CAPITAL_3 + CCAA_2 +CCAA_3 + CCAA_4 + CCAA_5 + CCAA_6 + CCAA_7 + CCAA_8 + CCAA_9 + CCAA_10 + CCAA_11 + CCAA_12 + CCAA_13 + CCAA_14 + CCAA_15 + CCAA_16 + CCAA_17 + CCAA_18 + CCAA_19  + P0A_2  + P14R_2 + P14R_3 + P14R_4 + P14R_5 + P14R_6 + P14R_7 + P14R_8 + P14R_9 + P14R_11 +  P14R_12 + P14R_17 + P14R_18 + P14R_95 + P14R_97  + P22_2   + P25_2 + P25_3 + P25_4 + P25_5 + P25_6 + P25_7  + P26_2 + P26_3 + P26_4 + P26_5 + P26_6 + P27_2  + P28_2 + P28_3', data=encuesta_dum).fit()
 
# Inspect the results
print(results.summary())

In [26]:
fueramodelo=["P27_2", "P28_2" , "P28_3", "TAMUNI" ,"P1", "P3"]
encuestapru=encuesta_dum.drop(columns=["P27_2", "P28_2" , "P28_3", "TAMUNI" ,"P1", "P3","ESTUDIOS"])

In [ ]:
modelos(encuestapru,"ideologia")

In [ ]:
def mejoresmodelos(data,columnadep):
    X=data.loc[:,data.columns!= columnadep]
    y=data[columnadep]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
    
    #modelos
    bosque100g=RandomForestClassifier(n_estimators=100, criterion='gini')
    bosque100e=RandomForestClassifier(n_estimators=100, criterion='entropy')
    bosque200g=RandomForestClassifier(n_estimators=200, criterion='gini')
    bosque200e=RandomForestClassifier(n_estimators=200, criterion='entropy')
    bosque500g=RandomForestClassifier(n_estimators=500, criterion='gini')
    bosque500e=RandomForestClassifier(n_estimators=500, criterion='entropy')
    bosque1000g=RandomForestClassifier(n_estimators=1000, criterion='gini')
    bosque1000e=RandomForestClassifier(n_estimators=1000, criterion='entropy')
    bosque2000g=RandomForestClassifier(n_estimators=2000, criterion='gini')
    bosque2000e=RandomForestClassifier(n_estimators=2000, criterion='entropy')
    #bosque2500=RandomForestClassifier(n_estimators=2500, criterion='gini')
    #bosque1500=RandomForestClassifier(n_estimators=1500, criterion='gini')
    gbcdev=GradientBoostingClassifier(loss='deviance')
    #gbcexpo=GradientBoostingClassifier(loss='exponential')

    #entrenando
    #bosque1500.fit(X_train, y_train) 
    #bosque2500.fit(X_train, y_train) 
    bosque100g.fit(X_train, y_train) 
    bosque100e.fit(X_train, y_train)
    bosque200g.fit(X_train, y_train) 
    bosque200e.fit(X_train, y_train)
    bosque500g.fit(X_train, y_train) 
    bosque500e.fit(X_train, y_train)
    bosque1000g.fit(X_train, y_train) 
    bosque1000e.fit(X_train, y_train)
    bosque2000g.fit(X_train, y_train) 
    bosque2000e.fit(X_train, y_train)
    #gbcdev.fit(X_train, y_train)
    #gbcexpo.fit(X_train, y_train)
    
    
    #y_pred_bosque1500= bosque1500.predict(X_test)
    #y_pred_bosque2500= bosque2500.predict(X_test)
    y_pred_bosque100g= bosque100g.predict(X_test)
    y_pred_bosque100e= bosque100e.predict(X_test)
    y_pred_bosque200g= bosque200g.predict(X_test)
    y_pred_bosque200e= bosque200e.predict(X_test)
    y_pred_bosque500g= bosque500g.predict(X_test)
    y_pred_bosque500e= bosque500e.predict(X_test)
    y_pred_bosque1000g= bosque1000g.predict(X_test)
    y_pred_bosque1000e= bosque1000e.predict(X_test)
    y_pred_bosque2000g= bosque2000g.predict(X_test)
    y_pred_bosque2000e= bosque2000e.predict(X_test)
    #y_pred_gbcdev=gbcdev.predict(X_test)
    #y_pred_gbcexpo=gbcexpo.predict(X_test)

    
    #print("Accuracy bosque1500:",metrics.accuracy_score(y_test, y_pred_bosque1500))
    #print("Accuracy bosque2500:",metrics.accuracy_score(y_test, y_pred_bosque2500))
    print("Accuracy bosque100g:",metrics.accuracy_score(y_test, y_pred_bosque100g))
    print("Accuracy bosque100e:",metrics.accuracy_score(y_test, y_pred_bosque100e))
    print("Accuracy bosque200g:",metrics.accuracy_score(y_test, y_pred_bosque200g))
    print("Accuracy bosque200e:",metrics.accuracy_score(y_test, y_pred_bosque200e))
    print("Accuracy bosque500g:",metrics.accuracy_score(y_test, y_pred_bosque500g))
    print("Accuracy bosque500e:",metrics.accuracy_score(y_test, y_pred_bosque500e))
    print("Accuracy bosque1000g:",metrics.accuracy_score(y_test, y_pred_bosque1000g))
    print("Accuracy bosque1000e:",metrics.accuracy_score(y_test, y_pred_bosque1000e))
    print("Accuracy bosque2000g:",metrics.accuracy_score(y_test, y_pred_bosque2000g))
    print("Accuracy bosque2000e:",metrics.accuracy_score(y_test, y_pred_bosque2000e))
    #print("Accuracy gbc_dev:",metrics.accuracy_score(y_test, y_pred_gbcdev))
   
    #print("Accuracy gbc_expo:",metrics.accuracy_score(y_test, y_pred_gbcexpo))
    


    # Your code here:
    print("matriz de confusion bosque100g","\n",confusion_matrix(y_test, y_pred_bosque100g))
    print("matriz de confusion bosque100e","\n",confusion_matrix(y_test, y_pred_bosque100e))
    print("matriz de confusion bosque200g","\n",confusion_matrix(y_test, y_pred_bosque200g))
    print("matriz de confusion bosque200e","\n",confusion_matrix(y_test, y_pred_bosque200e))
    print("matriz de confusion bosque500g","\n",confusion_matrix(y_test, y_pred_bosque500g))
    print("matriz de confusion bosque500e","\n",confusion_matrix(y_test, y_pred_bosque500e))
    print("matriz de confusion bosque1000g","\n",confusion_matrix(y_test, y_pred_bosque1000g))
    print("matriz de confusion bosque1000e","\n",confusion_matrix(y_test, y_pred_bosque1000e))
    print("matriz de confusion bosque2000g","\n",confusion_matrix(y_test, y_pred_bosque2000g))
    print("matriz de confusion bosque2000e","\n",confusion_matrix(y_test, y_pred_bosque2000e))
    
    #print("matriz de confusion bosque2500","\n",confusion_matrix(y_test, y_pred_bosque2500))
    #print("matriz de confusion bosque2000","\n",confusion_matrix(y_test, y_pred_bosque2000))
    #print("matriz de confusion gbc_dev","\n", confusion_matrix(y_test, y_pred_gbcdev))
    #print("matriz de confusion gbc_expo","\n", confusion_matrix(y_test, y_pred_gbcexpo))

In [ ]:
mejoresmodelos(encuestapru,"ideologia")

In [ ]:
'''X=encuestapru.loc[:,encuestapru.columns!='ideologia']
y=encuestapru['ideologia']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)'''

In [ ]:
'''grid_param = {  
    'n_estimators': [100, 300,1000,2000,5000],
    'criterion': ['gini', 'entropy'],   
    'bootstrap': [True, False]
}'''

In [ ]:
'''gd_sr = GridSearchCV(estimator=RandomForestClassifier(n_estimators=100),  
                     param_grid=grid_param,
                     scoring='accuracy',
                     cv=3,
                     n_jobs=-1) '''

In [ ]:
#gd_sr.fit(X_train, y_train)

In [ ]:
best_parameters = gd_sr.best_params_ 
best_parameters

In [ ]:
best_result = gd_sr.best_score_  
best_result

In [50]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters = 3)
temp_kmeans = kmeans.fit(encuestapru)
encuestapru['labels'] = temp_kmeans.labels_
encuestapru.labels.value_counts()

1    3863
2    2828
0    2704
Name: labels, dtype: int64

In [51]:
bla= pd.crosstab(encuestapru.ideologia, encuestapru.labels)
bla["total"]=bla.T.sum()
bla

labels        0     1     2  total
ideologia
0           826  1260   978   3064
1          1192  1922  1407   4521
2           686   681   443   1810

In [35]:
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler

In [52]:
model_db = DBSCAN(eps=0.5)
model_db = model_db.fit(encuestapru)

In [53]:
encuestapru['labels_DBSCAN'] = model_db.labels_

In [54]:
bla2= pd.crosstab(encuestapru.ideologia, encuestapru.labels_DBSCAN)
bla2["total"]=bla2.T.sum()
bla2

labels_DBSCAN    -1  total
ideologia
0              3064   3064
1              4521   4521
2              1810   1810

In [44]:
encuestapru['labels_DBSCAN'].value_counts()

-1    9395
Name: labels_DBSCAN, dtype: int64